In [1]:
import numpy as np 


arr = np.array([1, 2, 3, 4, 5,True,])
arrr2 = np.array([4,8.5,32,2,1,])
print(arr)

print(type(arr))
arrr2
arr.dtype

[1 2 3 4 5 1]
<class 'numpy.ndarray'>


dtype('int64')

In [2]:
arr.size # no.of elements



6

In [3]:
arr.ndim # to check the diminesion of array




1

In [4]:

print(np.__version__)

2.0.0


In [5]:
print(arr + 22)


[23 24 25 26 27 23]


In [6]:
(arr[1]) =  100
print(arr[1])

100


In [7]:
print(arrr2)
arrr2.dtype # to check datatype 


[ 4.   8.5 32.   2.   1. ]


dtype('float64')

2D ARRAYS

In [8]:
ls= [[1,3,5],
       [2,4,6],
       [0,8,9],
       [82,3,2,],
       [1,2,3,]]

ls


[[1, 3, 5], [2, 4, 6], [0, 8, 9], [82, 3, 2], [1, 2, 3]]

In [9]:
import numpy as np # type: ignore


In [10]:

print(arr1[0:,0:3])

NameError: name 'arr1' is not defined

In [ ]:
arr1[1,1:] = [6,4 ]
print(arr1[1,1:])

[6 4]


In [ ]:
print(arr1[1:3])

[[2 6 4]
 [0 8 9]]


In [ ]:
type(ls)


list

In [ ]:
arr1 = np.array(ls)
arr1

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [ 0,  8,  9],
       [82,  3,  2],
       [ 1,  2,  3]])

In [ ]:
arr1.shape

(5, 3)

In [ ]:
arr1.shape

(3, 3)

In [ ]:
arr1.ndim

2

In [ ]:
print(arrr2)
arrr2.dtype # to check datatype 


[ 4.   8.5 32.   2.   1. ]


dtype('float64')

In [ ]:
arr = np.random.randint(1,200,500)
arr

array([110,  96,  48,  49, 176, 145,  61,  26, 120,  98, 100, 151, 133,
       158, 164, 197, 155, 196, 191,  37,   3, 179,  45,  92,  72, 117,
       157,  55, 196, 180, 191, 112,  70, 188,  52,  61,  42,  79,  92,
       129, 142,  45, 196, 161,   8, 130,  82,  27,  61, 132,  23,  35,
        38, 102,  47,  15, 131, 195,  60, 151,  90, 150, 115, 134, 124,
       142, 155, 143,  60, 174,  85,  43, 153,  83,  40,   6,   5, 122,
        71, 129, 176, 117, 150,  96,  76,  86, 132,  41, 136,  73, 128,
       198, 134, 188, 106, 169,  60,  39,  83,  71, 110, 109, 108,  58,
        62, 166, 150, 137,  43,   4, 196,  10,   3,   5, 197, 132, 158,
        11, 130,  66,  79, 136,  11, 198, 124, 157,  72,  22, 159,  45,
        56,  79,  42, 155,  23,  74, 167, 118, 183,  16,  33, 159,  30,
        26, 170, 128,  96,  77, 169, 166,  43,  75, 107,  44, 152,  76,
        14, 181, 172, 129,  59,   9,  30, 122, 131,  59, 137,  85, 112,
        28,  54, 120, 136, 157, 169,   3, 113, 193, 167, 174, 13

IndentationError: unindent does not match any outer indentation level (<string>, line 5)

In [ ]:
arr[arr <=100]

array([ 96,  48,  49,  61,  26,  98, 100,  37,   3,  45,  92,  72,  55,
        70,  52,  61,  42,  79,  92,  45,   8,  82,  27,  61,  23,  35,
        38,  47,  15,  60,  90,  60,  85,  43,  83,  40,   6,   5,  71,
        96,  76,  86,  41,  73,  60,  39,  83,  71,  58,  62,  43,   4,
        10,   3,   5,  11,  66,  79,  11,  72,  22,  45,  56,  79,  42,
        23,  74,  16,  33,  30,  26,  96,  77,  43,  75,  44,  76,  14,
        59,   9,  30,  59,  85,  28,  54,   3,   9,  69,  97,  95,  21,
        95,  48,  71,  23,  27,  45,  23,  91,  53,   1,  48,  77,  67,
        79,  60,  81,  48,  57,   2,  58,  50,   4,   1,   4,  84,  89,
        22,  74,  52,  41,  59,  54,  36,  83,  39,  18,  22,  81,  64,
        72,   7,  85,  53,  44,  96,  67,  45,  39,   8,  39,  12,   7,
         9,  49,  71,  55,  48,  26,  54,  48,  12,  77,  23,  14,  70,
        83,  93,  10,   4,  60,  48,  34,  67,   4,   6,  90,  33,  70,
        74,  50,   9,  39,  25,  30,  88,  80,  21,  52,  97,  1

In [ ]:
arr[arr <= 100].size

240

In [ ]:
arr[arr <= 100].shape

(240,)

In [ ]:
arr[arr > 100].size

260

In [ ]:
len(arr <= 100)

500

In [ ]:
arr3 = np.random.randint(1,200,(10,5))
arr3

array([[198,  64, 103,  96, 107],
       [155,  40,  43,  26,   2],
       [175, 161,  61,  24,  61],
       [179,  67,  26, 134, 185],
       [189, 141, 153, 100,   8],
       [ 87,  81, 193, 129, 117],
       [146,  39, 162,  18, 139],
       [145, 163,  64,  94, 126],
       [172, 182,  44,  40,  44],
       [171,  30, 181,  62, 172]], dtype=int32)

In [ ]:
arr_zero = np.zeros(10)
arr_zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr_zero = np.zeros((10,3))
arr_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

TypeError: 'list' object is not callable

In [ ]:
ar1 = np.arange(25)
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

NameError: name 'ar1' is not defined

In [ ]:
import numpy as np
arr3 = np.random.randint(1,200,(3,5,3))
arr3

array([[[ 27,  85,  99],
        [ 54, 177,  14],
        [ 81, 121,   1],
        [ 20,  95,  32],
        [175, 116,  20]],

       [[  6,  45,   8],
        [111, 138, 103],
        [ 27, 160, 179],
        [ 35,  97, 116],
        [  8, 114,  31]],

       [[168,  96,  99],
        [ 68,  25,  34],
        [138, 198, 157],
        [124,   7,   3],
        [180, 115,   9]]], dtype=int32)

In [ ]:
arr3[2,0:2,1:3]
     

array([[96, 99],
       [25, 34]], dtype=int32)

In [ ]:
arr3.shape

(3, 5, 3)

In [ ]:
arr3[0:,0]

arr3

array([[[ 27,  85,  99],
        [ 54, 177,  14],
        [ 81, 121,   1],
        [ 20,  95,  32],
        [175, 116,  20]],

       [[  6,  45,   8],
        [111, 138, 103],
        [ 27, 160, 179],
        [ 35,  97, 116],
        [  8, 114,  31]],

       [[168,  96,  99],
        [ 68,  25,  34],
        [138, 198, 157],
        [124,   7,   3],
        [180, 115,   9]]], dtype=int32)

In [ ]:
arr3[:,-5,:]

array([[ 27,  85,  99],
       [  6,  45,   8],
       [168,  96,  99]], dtype=int32)

In [ ]:
arr = np.array([711,82,91])
arr

array([711,  82,  91])

In [ ]:
min(arr)

np.int64(82)

In [ ]:
np.sum(arr)

np.int64(884)

In [ ]:
np.mean(arr)

np.float64(19.0)

In [ ]:
max(arr)

np.int64(100)

In [ ]:
arr.sort

<function ndarray.sort>

In [ ]:
arr.sort()
arr

array([ 82,  91, 711])